spring.application.name=user-api

spring.datasource.url=jdbc:postgresql://localhost:5432/user_api_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
